need to quote DOCKER_OPTS and throwing in daemon_arg for good measure
Signed-off-by: Chase Bolt <chase.bolt@gmail.com>

diff --git a/templates/default/sysvinit/docker-debian.erb b/templates/default/sysvinit/docker-debian.erb
--- a/templates/default/sysvinit/docker-debian.erb
+++ b/templates/default/sysvinit/docker-debian.erb
@@ -23,7 +23,7 @@ BASE=<%= @docker_name %>
 
 # modify these in /etc/default/$BASE (/etc/default/docker)
 DOCKER=<%= @dockerd_bin_link %>
-DOCKER_OPTS=<%= @docker_daemon_arg %>
+DOCKER_OPTS="<%= @docker_daemon_arg %> <%= @docker_daemon_opts %>"
 # This is the pid file managed by docker itself
 DOCKER_PIDFILE=/var/run/$BASE.pid
 # This is the pid file created/managed by start-stop-daemon
@@ -110,7 +110,12 @@ case "$1" in
                         $DOCKER_OPTS \
                         -p "$DOCKER_PIDFILE" \
                         >> "$DOCKER_LOGFILE" 2>&1
-    <%= @docker_wait_ready %>
+
+    <%= @docker_wait_ready %> > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+      log_failure_msg "<%= @docker_socket %> failed to start"
+      exit 1
+    fi
     log_end_msg $?
     ;;
 
